FROM golang:1.24-alpine AS builder

ENV GOPROXY=https://package-mirror.liara.ir/repository/go/

# 1. COPY ONLY go.mod and go.sum files first
WORKDIR /app
COPY api_gateway/go.mod api_gateway/go.sum ./api_gateway/
COPY pkg/go.mod pkg/go.sum ./pkg/


# 2. Download dependencies
WORKDIR /app/api_gateway
RUN --mount=type=cache,target=/go/pkg/mod go mod download

# 3. NOW copy the rest of the application source code
WORKDIR /app
COPY pkg ./pkg
COPY api_gateway ./api_gateway

WORKDIR /app/api_gateway

# 4. Build the application
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o main ./cmd

# 5. Use a smaller image for the final container
FROM alpine:latest

# 6. Copy required files and setting to the final project
WORKDIR /app


# Copy binary from builder
WORKDIR /app/api_gateway
COPY --from=builder /app/api_gateway/main ./main
 
EXPOSE 8080

CMD ["./main"]