CREATE TABLE Users (
	ID UUID PRIMARY KEY,
	Email VARCHAR(255) NOT NULL,
	PASSWORD_HASH  VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT NOW(),
	UPDATED_AT TIMESTAMP DEFAULT NOW(),
	UNIQUE (Email)
)
