CREATE TABLE DIRECTORIES_METADATA (
	ID UUID PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL,
	HASH VARCHAR(256),
	CREATED_AT TIMESTAMP DEFAULT NOW(),
	Size INTEGER NOT NULL,
	PARENT_ID UUID NULL,
	UNIQUE (HASH),
	CONSTRAINT FK_PARENT FOREIGN KEY (PARENT_ID) REFERENCES DIRECTORIES_METADATA(ID) ON DELETE RESTRICT
);

CREATE TABLE FILES_METADATA (
	ID UUID PRIMARY KEY,
	STORAGE_ID UUID NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	FILE_EXTENSION VARCHAR(255) NOT NULL,
	CONTENT_TYPE SMALLINT NOT NULL,
    Size INTEGER NOT NULL,
    DRIVE VARCHAR(255) NOT NULL,
	HASH VARCHAR(256),
	CREATED_AT TIMESTAMP DEFAULT NOW(),
	UPDATE_AT TIMESTAMP DEFAULT NOW(),
	DIRECTORY_ID UUID,
	UNIQUE (HASH),
	CONSTRAINT FK_DIRECTORY FOREIGN KEY (DIRECTORY_ID) REFERENCES DIRECTORIES_METADATA(ID) ON DELETE RESTRICT
);